LineLength:
  Max: 160
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

SpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
